### ISSUE TITLE
[BUG] Excessive slow-down of the server

### ISSUE THREAD

**Issue by Amaras** [pascalaubry/papi-web#48]
When using the server, after a while, the server starts slowing down.

I have not experienced it yet, but reports from at least 2 different users (including @pascalaubry, please edit with more details when you have the time) confirmed the slow-down.

I suspect a memory leak somewhere in the server process, and will try to investigate it further.

**Comment by pascalaubry** [comment]
I faced this problem on nov. 10th but the reason was my OneDrive synchronization coupled with Windows updates.
Removing screen set refreshers also helped in reducing the server load.
I think this issue could be closed now, at least I mark it as fixed (@Amaras please tell us if you face the problem again next week).
